import type { Metadata } from "next";
import { Courier_Prime, Outfit } from "next/font/google";
import Image from 'next/image'
import Link from 'next/link'
import "./globals.css";
import styles from "./page.module.scss";

const courierPrime = Courier_Prime({
  variable: "--font-courier-prime",
  weight: ['400', '700'],
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  weight: ['400', '700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ashlie Webb | Frontend Developer & UX Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${courierPrime.variable}`}>
        <div className={styles.page}>
          <div className={styles.strapline}>
            <p>Crafting meaningful online experiences since 2009</p>
          </div>
          <header className={styles.header}>
            <Link href="/">
              <Image
                className={styles.logo}
                src="/logo.svg"
                alt="Ashlie Webb Designs"
                width={146}
                height={80}
                priority
              />
            </Link>
            <ul className={styles.navigation}>
              <li>
                <Link href="/skills" className={styles.navigationLink}>Skills</Link>
              </li>
              <li>
                <Link href="/portfolio" className={styles.navigationLink}>Portfolio</Link>
              </li>
              <li>
                <Link href="/contact" className={styles.buttonPrimary}>Get In Touch</Link>
              </li>
            </ul>
          </header>
          <main className={styles.main}>
            {children}
          </main>
          <footer className={styles.footer}>
            <p>&copy; Ashlie Webb 2025</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
